// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protobuf/drawing_share.proto

package grpc_example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Data *DotData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ConnectResponse) GetData() *DotData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DisConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *DisConnectRequest) Reset() {
	*x = DisConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisConnectRequest) ProtoMessage() {}

func (x *DisConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisConnectRequest.ProtoReflect.Descriptor instead.
func (*DisConnectRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{2}
}

func (x *DisConnectRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type DisConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DisConnectResponse) Reset() {
	*x = DisConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisConnectResponse) ProtoMessage() {}

func (x *DisConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisConnectResponse.ProtoReflect.Descriptor instead.
func (*DisConnectResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{3}
}

func (x *DisConnectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendDrawingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *DotData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	From string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *SendDrawingRequest) Reset() {
	*x = SendDrawingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDrawingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDrawingRequest) ProtoMessage() {}

func (x *SendDrawingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDrawingRequest.ProtoReflect.Descriptor instead.
func (*SendDrawingRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{4}
}

func (x *SendDrawingRequest) GetData() *DotData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendDrawingRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type DotData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *DotData) Reset() {
	*x = DotData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotData) ProtoMessage() {}

func (x *DotData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotData.ProtoReflect.Descriptor instead.
func (*DotData) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{5}
}

func (x *DotData) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DotData) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SendDrawingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SendDrawingResponse) Reset() {
	*x = SendDrawingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_drawing_share_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDrawingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDrawingResponse) ProtoMessage() {}

func (x *SendDrawingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_drawing_share_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDrawingResponse.ProtoReflect.Descriptor instead.
func (*SendDrawingResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_drawing_share_proto_rawDescGZIP(), []int{6}
}

func (x *SendDrawingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protobuf_drawing_share_proto protoreflect.FileDescriptor

var file_protobuf_drawing_share_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x24, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x2c, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x54, 0x0a,
	0x12, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x2e, 0x44, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x22, 0x25, 0x0a, 0x07, 0x44, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x79, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x65,
	0x6e, 0x64, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x83, 0x02, 0x0a, 0x0c, 0x44, 0x72,
	0x61, 0x77, 0x69, 0x6e, 0x67, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x54, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x72,
	0x61, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x72, 0x61, 0x77, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x72, 0x61,
	0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0a,
	0x44, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x20, 0x2e, 0x64, 0x72, 0x61,
	0x77, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64,
	0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x69, 0x73,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x28, 0x5a, 0x26, 0x73, 0x68, 0x75, 0x6b, 0x75, 0x62, 0x6f, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x2d,
	0x61, 0x70, 0x69, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobuf_drawing_share_proto_rawDescOnce sync.Once
	file_protobuf_drawing_share_proto_rawDescData = file_protobuf_drawing_share_proto_rawDesc
)

func file_protobuf_drawing_share_proto_rawDescGZIP() []byte {
	file_protobuf_drawing_share_proto_rawDescOnce.Do(func() {
		file_protobuf_drawing_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_drawing_share_proto_rawDescData)
	})
	return file_protobuf_drawing_share_proto_rawDescData
}

var file_protobuf_drawing_share_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_drawing_share_proto_goTypes = []interface{}{
	(*ConnectRequest)(nil),      // 0: drawing_share.ConnectRequest
	(*ConnectResponse)(nil),     // 1: drawing_share.ConnectResponse
	(*DisConnectRequest)(nil),   // 2: drawing_share.DisConnectRequest
	(*DisConnectResponse)(nil),  // 3: drawing_share.DisConnectResponse
	(*SendDrawingRequest)(nil),  // 4: drawing_share.SendDrawingRequest
	(*DotData)(nil),             // 5: drawing_share.DotData
	(*SendDrawingResponse)(nil), // 6: drawing_share.SendDrawingResponse
}
var file_protobuf_drawing_share_proto_depIdxs = []int32{
	5, // 0: drawing_share.ConnectResponse.data:type_name -> drawing_share.DotData
	5, // 1: drawing_share.SendDrawingRequest.data:type_name -> drawing_share.DotData
	0, // 2: drawing_share.DrawingShare.Connect:input_type -> drawing_share.ConnectRequest
	4, // 3: drawing_share.DrawingShare.SendDrawing:input_type -> drawing_share.SendDrawingRequest
	2, // 4: drawing_share.DrawingShare.DisConnect:input_type -> drawing_share.DisConnectRequest
	1, // 5: drawing_share.DrawingShare.Connect:output_type -> drawing_share.ConnectResponse
	6, // 6: drawing_share.DrawingShare.SendDrawing:output_type -> drawing_share.SendDrawingResponse
	3, // 7: drawing_share.DrawingShare.DisConnect:output_type -> drawing_share.DisConnectResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_drawing_share_proto_init() }
func file_protobuf_drawing_share_proto_init() {
	if File_protobuf_drawing_share_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_drawing_share_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_drawing_share_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_drawing_share_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_drawing_share_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_drawing_share_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDrawingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_drawing_share_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DotData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_drawing_share_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDrawingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_drawing_share_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_drawing_share_proto_goTypes,
		DependencyIndexes: file_protobuf_drawing_share_proto_depIdxs,
		MessageInfos:      file_protobuf_drawing_share_proto_msgTypes,
	}.Build()
	File_protobuf_drawing_share_proto = out.File
	file_protobuf_drawing_share_proto_rawDesc = nil
	file_protobuf_drawing_share_proto_goTypes = nil
	file_protobuf_drawing_share_proto_depIdxs = nil
}
