/**
 * @fileoverview gRPC-Web generated client stub for proto.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: protobuf/v1/receptions.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protobuf_v1_receptions_pb from '../../protobuf/v1/receptions_pb';


export class ReceptionServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorReceptionList = new grpcWeb.MethodDescriptor(
    '/proto.v1.ReceptionService/ReceptionList',
    grpcWeb.MethodType.UNARY,
    protobuf_v1_receptions_pb.ReceptionListRequest,
    protobuf_v1_receptions_pb.ReceptionListResponse,
    (request: protobuf_v1_receptions_pb.ReceptionListRequest) => {
      return request.serializeBinary();
    },
    protobuf_v1_receptions_pb.ReceptionListResponse.deserializeBinary
  );

  receptionList(
    request: protobuf_v1_receptions_pb.ReceptionListRequest,
    metadata: grpcWeb.Metadata | null): Promise<protobuf_v1_receptions_pb.ReceptionListResponse>;

  receptionList(
    request: protobuf_v1_receptions_pb.ReceptionListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protobuf_v1_receptions_pb.ReceptionListResponse) => void): grpcWeb.ClientReadableStream<protobuf_v1_receptions_pb.ReceptionListResponse>;

  receptionList(
    request: protobuf_v1_receptions_pb.ReceptionListRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protobuf_v1_receptions_pb.ReceptionListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.v1.ReceptionService/ReceptionList',
        request,
        metadata || {},
        this.methodDescriptorReceptionList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.v1.ReceptionService/ReceptionList',
    request,
    metadata || {},
    this.methodDescriptorReceptionList);
  }

}

