version: '3'
services:
  app:
    container_name: protobuf-builder
    build: .
    volumes:
      - type: bind
        source: .
        target: /var/work
    working_dir: /var/work
    entrypoint: bash
    stdin_open: true
    tty: true

